config/routes.rb
Rails.application.routes.draw do
	namespace :api, defaults: {format: :json} do
		resources :people, except: [:new, :edit]
		resources :vehicles, except: [:new, :edit]
		resources :driver_histories, except: [:new, :edit]
		resources :quotes, except: [:new, :edit]
	end
  resources :driver_histories
  resources :vehicles
  resources :people
  resources :quotes

  root 'quotes#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/quote.rb
class Quote < ApplicationRecord
	#Quotes have one of each other model. Not necessary in this iteration per se, but in future iterations where accounts could log their quotes, this can be used to retreive them.
	has_one :person
	has_one :vehicle
	has_one :driver_history

	#Accepting nested attributes is how the quote#new page can handle the creation of the person, vehicle, and driver history models as well as its own. This makes the site far more intuitive than having separate pages for each model, passing values on until reaching Quote to give a verdict. This makes that much cleaner.
	accepts_nested_attributes_for :person, :vehicle, :driver_history

	#This is here to update the Quote with the relevant date and Premium value upon being created on the quote#new page.
	def update(value)
		self.premium = value
		self.date_created = Date.today
	end
end

app/controllers/api/quotes_controller.rb
module Api
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :update, :destroy]

  # GET /quotes
  def index
    quotes = Quote.all

    render json: {status: 'SUCCESS', message:'Loaded quotes', data:quotes},status: :ok
  end

  # GET /quotes/1
  def show
	  quote = Quote.find(params[:id])
    render json: {status: 'SUCCESS', message:'Loaded quote', data:quote},status: :ok
  end

  # POST /quotes
  def create
    quote = Quote.new(quote_params) 
    if quote.save  
    render json: {istatus: 'SUCCESS', message:'Saved quote', data:quote},status: :ok
    else  
	    render json: {status: 'ERROR', message:'Did nto save quote', data:quote.errors},status: :unprocessable_entity
    end
  end

  # PATCH/PUT /quotes/1
  def update
	  quote = Quote.find(params[:id])
    if quote.update(quote_params)  
    render json: {status: 'SUCCESS', message:'Updated quote', data:quote},status: :ok
    else 
	    render json: {status: 'ERROR', message:'Did not update quote', data:quote.errors},status: :unprocessable_entity
    end
  end

  # DELETE /quotes/1
  def destroy
	  quote = Quote.find(params[:id])
    quote.destroy
    render json: {status: 'SUCCESS', message:'Deleted quote', data:quote},status: :ok
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def quote_params
      params.require(:quote).permit(:premium, :date_created, :vehicle_id, :driver_history, :person)
    end
end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
	before_action :set_quote, only: [:show, :edit, :update, :destroy]

	# GET /quotes
	# GET /quotes.json
	def index
		@quotes = Quote.all
	end

	# GET /quotes/1
	# GET /quotes/1.json
	def show
	end

	# GET /quotes/new
	def new
		@quote = Quote.new
		@quote.build_vehicle
		@quote.build_person
		@quote.build_driver_history
	end

	# GET /quotes/1/edit
	def edit
	end

	# POST /quotes
	# Create has been updated to fit with my 2 webpage design, where all the models are created on 1 page, and showing the quote created once the details have been entered. This passes parameters entered on the page into the quote's update function. Weird side effect, instead of adding the numbers, it concatenates the numbers. Ruby is strange.
	def create
		@quote = Quote.new(quote_params)
		@quote.update((quote_params[:vehicle_attributes][:value])+(quote_params[:driver_history_attributes][:value])+(quote_params[:vehicle_attributes][:mileage]))
		respond_to do |format|
			if @quote.save
				format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
			else
				format.html { render :new }
				format.json { render json: @quote.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /quotes/1
	# PATCH/PUT /quotes/1.json
	def update
		respond_to do |format|
			if @quote.update(quote_params)
				format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
				format.json { render :show, status: :ok, location: @quote }
			else
				format.html { render :edit }
				format.json { render json: @quote.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /quotes/1
	# DELETE /quotes/1.json
	def destroy
		@quote.destroy
		respond_to do |format|
			format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_quote
		@quote = Quote.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def quote_params
		params.require(:quote).permit(:date_created, :premium, vehicle_attributes:[:registration, :value, :parking_location, :mileage, :policy_start], driver_history_attributes:[:date_of_incident, :value, :description, :incident_type], person_attributes:[:title, :forename, :surname, :email, :license_period, :telephone, :date_of_birth, :license_type, :street, :city, :county, :postcode, :occupation])
	end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_with(model: quote, local: true) do |form| %>
 <% if quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date_created %>
    <%= form.date_select :date_created %>
  </div>

  <div class="field">
    <%= form.label :premium %>
    <%= form.number_field :premium %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quotes</h1>

<table>
  <thead>
    <tr>
      <th>Date created</th>
      <th>Premium</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.date_created %></td>
        <td><%= quote.premium %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>Welcome to Andy's Insurance Quotations!</h1>
<h2>Please enter your details below</h2>
<h3>We promise not to steal and sell all your data</h3>

<!--<%= render 'form', quote: @quote %>

<%= link_to 'Back', quotes_path %>-->
<!--
	For this view, any and all errors from any of the models missing validates_presence_of requirements are caught, one of the challenges I was worried about when creating this project. It also pushes all parameters through Quotes, so that Quote may fetch the parameters it needs to calculate the premium, before going off to create their respective objects.
-->
<%= form_for @quote do |f| %>
	<% if @quote.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

			<ul>
				<% @quote.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<b>Person Insured</b>
	<%= f.fields_for :person do |person| %>
		<div class="field">
			<%= person.label :title%>
			<%= person.text_field :title%>
		</div>
		<div class="field">
			<%= person.label :forename%>
			<%= person.text_field :forename%>
		</div>
		<div class="field">
			<%= person.label :surname%>
			<%= person.text_field :surname%>
		</div>
		<div class="field">
			<%= person.label :email%>
			<%= person.text_field :email%>
		</div>
		<div class="field">
			<%= person.label :license_period%>
			<%= person.number_field :license_period%>
		</div>
		<div class="field">
			<%= person.label :telephone%>
			<%= person.text_field :telephone%>
		</div>
		<div class="field">
			<%= person.label :date_of_birth%>
			<%= person.date_select :date_of_birth%>
		</div>
		<div class="field">
			<%= person.label :license_type%>
			<%= person.text_field :license_type%>
		</div>
		<div class="field">
			<%= person.label :street%>
			<%= person.text_field :street%>
		</div>
		<div class="field">
			<%= person.label :city%>
			<%= person.text_field :city%>
		</div>
		<div class="field">
			<%= person.label :county%>
			<%= person.text_field :county%>
		</div>
		<div class="field">
			<%= person.label :postcode%>	
			<%= person.text_field :postcode%>
		</div>
		<div class="field">
			<%= person.label :occupation%>
			<%= person.text_field :occupation%>
		</div>
	<% end %>
	<b>Vehicle Details</b>
	<%= f.fields_for :vehicle do |vehicle|%>
		<div class="field">
			<%= vehicle.label :registration%>
			<%= vehicle.text_field :registration%>
		</div>
		<div class="field">
			<%= vehicle.label :mileage%>
			<%= vehicle.number_field :mileage%>
		</div>
		<div class="field">
			<%= vehicle.label :value%>
			<%= vehicle.number_field :value%>
		</div>
		<div class="field">
			<%= vehicle.label :parking_location%>
			<%= vehicle.text_field :parking_location%>
		</div>
		<div class="field">
			<%= vehicle.label :policy_start%>
			<%= vehicle.date_select :policy_start%>
		</div>
	<% end %>
	<b>Driver History</b>
	<%= f.fields_for :driver_history do |driver_history|%>
		<div class="field">
			<%= driver_history.label :description%>
			<%= driver_history.text_field :description%>
		</div>
		<div class="field">
			<%= driver_history.label :incident_type%>		
			<%= driver_history.text_field :incident_type%>
		</div>
		<div class="field">
			<%= driver_history.label :date_of_incident%>	
			<%= driver_history.date_select :date_of_incident%>
		</div>
		<div class="field">
			<%= driver_history.label :value%>
			<%= driver_history.number_field :value%>
		</div>
	<% end %>
	<%= f.submit %>
<% end %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date created:</strong>
  <%= @quote.date_created %>
</p>

<p>
  <strong>Premium:</strong>
  <%= @quote.premium %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>