config/routes.rb
Rails.application.routes.draw do
	namespace :api, defaults: {format: :json} do
		resources :people, except: [:new, :edit]
		resources :vehicles, except: [:new, :edit]
		resources :driver_histories, except: [:new, :edit]
		resources :quotes, except: [:new, :edit]
	end
  resources :driver_histories
  resources :vehicles
  resources :people
  resources :quotes

  root 'quotes#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/driver_history.rb
class DriverHistory < ApplicationRecord
	validates_presence_of :value, :description

	belongs_to :quote, optional: true
end

app/controllers/api/driver_histories_controller.rb
module Api
class DriverHistoriesController < ApplicationController
  before_action :set_driver_history, only: [:show, :update, :destroy]

  # GET /driver_histories
  def index
    driver_histories = DriverHistory.all 
	    render json: {status: 'SUCCESS', message:'Loaded driver histories', data:driver_histories},status: :ok
  end

  # GET /driver_histories/1
  def show
	  driver_history = DriverHistory.find(params[:id])
	    render json: {status: 'SUCCESS', message:'Loaded driver history', data:driver_history},status: :ok
  end

  # POST /driver_histories
  def create
    driver_history = DriverHistory.new(driver_history_params)

    if driver_history.save
	    render json: {status: 'SUCCESS', message:'Created driver history', data:driver_history},status: :ok
    else
	    render json: {status: 'ERROR', message:'Failed to create driver history', data:driver_history.errors},status: :unprocessable_entity
    end
  end

  # PATCH/PUT /driver_histories/1
  def update
	  driver_history = DriverHistory.find(params[:id])
    if @driver_history.update(driver_history_params)
	    render json: {status: 'SUCCESS', message:'Updated driver history', data:driver_history},status: :ok
    else
	    render json: {status: 'ERROR', message:'Failed to update driver history', data:driver_history.errors},status: :unprocessable_entity
    end
  end

  # DELETE /driver_histories/1
  def destroy 
	  driver_history = DriverHistory.find(params[:id])
	  driver_history.destroy
	    render json: {status: 'SUCCESS', message:'Deleted driver history', data:driver_history},status: :ok
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_driver_history
      driver_history = DriverHistory.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def driver_history_params
      params.require(:driver_history).permit(:date_of_incident, :value, :incident_type, :description)
    end
end
end

app/controllers/driver_histories_controller.rb
class DriverHistoriesController < ApplicationController
  before_action :set_driver_history, only: [:show, :edit, :update, :destroy]

  # GET /driver_histories
  # GET /driver_histories.json
  def index
    @driver_histories = DriverHistory.all
  end

  # GET /driver_histories/1
  # GET /driver_histories/1.json
  def show
  end

  # GET /driver_histories/new
  def new
    @driver_history = DriverHistory.new
  end

  # GET /driver_histories/1/edit
  def edit
  end

  # POST /driver_histories
  # POST /driver_histories.json
  def create
    @driver_history = DriverHistory.new(driver_history_params)

    respond_to do |format|
      if @driver_history.save
        format.html { redirect_to quote_url(:new), notice: 'Driver history was successfully created.' }
        format.json { render :show, status: :created, location: @driver_history }
      else
        format.html { render :new }
        format.json { render json: @driver_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /driver_histories/1
  # PATCH/PUT /driver_histories/1.json
  def update
    respond_to do |format|
      if @driver_history.update(driver_history_params)
        format.html { redirect_to @driver_history, notice: 'Driver history was successfully updated.' }
        format.json { render :show, status: :ok, location: @driver_history }
      else
        format.html { render :edit }
        format.json { render json: @driver_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /driver_histories/1
  # DELETE /driver_histories/1.json
  def destroy
    @driver_history.destroy
    respond_to do |format|
      format.html { redirect_to driver_histories_url, notice: 'Driver history was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_driver_history
      @driver_history = DriverHistory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def driver_history_params
      params.require(:driver_history).permit(:date_of_incident, :value, :description, :incident_type)
    end
end

app/helpers/driver_histories_helper.rb
module DriverHistoriesHelper
end

app/views/driver_histories/_form.html.erb
<%= form_with(model: driver_history, local: true) do |form| %>
  <% if driver_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(driver_history.errors.count, "error") %> prohibited this driver_history from being saved:</h2>

      <ul>
      <% driver_history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date_of_incidient %>
    <%= form.date_select :date_of_incidient %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.number_field :value %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :incident_type %>
    <%= form.text_field :incident_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/driver_histories/edit.html.erb
<h1>Editing Driver History</h1>

<%= render 'form', driver_history: @driver_history %>

<%= link_to 'Show', @driver_history %> |
<%= link_to 'Back', driver_histories_path %>

app/views/driver_histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Driver Histories</h1>

<table>
  <thead>
    <tr>
      <th>Date of incident</th>
      <th>Value</th>
      <th>Description</th>
      <th>Incident type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @driver_histories.each do |driver_history| %>
      <tr>
        <td><%= driver_history.date_of_incident %></td>
        <td><%= driver_history.value %></td>
        <td><%= driver_history.description %></td>
        <td><%= driver_history.incident_type %></td>
        <td><%= link_to 'Show', driver_history %></td>
        <td><%= link_to 'Edit', edit_driver_history_path(driver_history) %></td>
        <td><%= link_to 'Destroy', driver_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Driver History', new_driver_history_path %>

app/views/driver_histories/new.html.erb
<h1>New Driver History</h1>

<%= render 'form', driver_history: @driver_history %>

<%= link_to 'Back', driver_histories_path %>

app/views/driver_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date of incident:</strong>
  <%= @driver_history.date_of_incident %>
</p>

<p>
  <strong>Value:</strong>
  <%= @driver_history.value %>
</p>

<p>
  <strong>Description:</strong>
  <%= @driver_history.description %>
</p>

<p>
  <strong>Incident type:</strong>
  <%= @driver_history.incident_type %>
</p>

<%= link_to 'Edit', edit_driver_history_path(@driver_history) %> |
<%= link_to 'Back', driver_histories_path %>