config/routes.rb
Rails.application.routes.draw do
	namespace :api, defaults: {format: :json} do
		resources :people, except: [:new, :edit]
		resources :vehicles, except: [:new, :edit]
		resources :driver_histories, except: [:new, :edit]
		resources :quotes, except: [:new, :edit]
	end
  resources :driver_histories
  resources :vehicles
  resources :people
  resources :quotes

  root 'quotes#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/person.rb
class Person < ApplicationRecord
	validates_presence_of :title, :forename, :surname, :email, :license_period
	#Validate a real email is being used, with extra appendices allowed to allow emails such as .co.uk or @aber.ac.uk
	validates_format_of :email, with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i, message: 'Please enter a valid email'

	belongs_to :quote, optional: true
end

app/controllers/api/people_controller.rb
module Api
	class PeopleController < ApplicationController
		before_action :set_person, only: [:show, :update, :destroy]

def index
	people = Person.all
	render json: {status: 'SUCCESS', message:'Loaded people', data:people},status: :ok
end
		
def show
	person = Person.find(params[:id])
		render json: {status: 'SUCCESS', message:'Loaded person', data:person},status: :ok
	end

	def create
		person = Person.new(person_params)
			
		if person.save
			render json: {status: 'SUCESS', message:'Saved person', data:person},status: :ok
		else
			render json: {status: 'ERROR', message:'Person not saved', data:person.errors},status: :unprocessable_entity
		end
	end

	def destroy
		person = Person.find(params[:id])
		person.destroy
		render json: {status: 'SUCCESS', message:'Deleted person', data:person},status: :ok
	end

	def update
		person = Person.find(params[:id])
		if person.update_attributes(person_params)
			render json: {status: 'SUCCESS', message:'Updated person', data:person},status: :ok
		else
			render json: {status: 'ERROR', message:'Person not updated', data:person.errors},status: :unprocessable_entity
		end
	end

	private
	def set_person
		@person = Person.find(params[:id])
	end

	def person_params
		params.require(:person).permit(:title, :forename, :surname, :email, :date_of_birth, :telephone, :street, :city, :county, :postcode, :license_type, :license_period, :occupation)
	end
	end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  #
  # When a new person is created, it will then prompt the user to create a new vehicle as well.
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
	format.html { redirect_to vehicle_url(:new), notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:title, :forename, :surname, :email, :telephone, :date_of_birth, :license_type, :occupation, :street, :city, :county, :license_period, :postcode)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :forename %>
    <%= form.text_field :forename %>
  </div>

  <div class="field">
    <%= form.label :surname %>
    <%= form.text_field :surname %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :telephone %>
    <%= form.text_field :telephone %>
  </div>

  <div class="field">
    <%= form.label :date_of_birth %>
    <%= form.date_select :date_of_birth %>
  </div>

  <div class="field">
    <%= form.label :license_type %>
    <%= form.text_field :license_type %>
  </div>

  <div class="field">
    <%= form.label :occupation %>
    <%= form.text_field :occupation %>
  </div>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :county %>
    <%= form.text_field :county %>
  </div>

  <div class="field">
    <%= form.label :license_period %>
    <%= form.number_field :license_period %>
  </div>

  <div class="field">
    <%= form.label :postcode %>
    <%= form.text_field :postcode %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Forename</th>
      <th>Surname</th>
      <th>Email</th>
      <th>Telephone</th>
      <th>Date of birth</th>
      <th>License type</th>
      <th>Occupation</th>
      <th>Street</th>
      <th>City</th>
      <th>County</th>
      <th>License period</th>
      <th>Postcode</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.title %></td>
        <td><%= person.forename %></td>
        <td><%= person.surname %></td>
        <td><%= person.email %></td>
        <td><%= person.telephone %></td>
        <td><%= person.date_of_birth %></td>
        <td><%= person.license_type %></td>
        <td><%= person.occupation %></td>
        <td><%= person.street %></td>
        <td><%= person.city %></td>
        <td><%= person.county %></td>
        <td><%= person.license_period %></td>
        <td><%= person.postcode %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @person.title %>
</p>

<p>
  <strong>Forename:</strong>
  <%= @person.forename %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @person.surname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @person.email %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @person.telephone %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @person.date_of_birth %>
</p>

<p>
  <strong>License type:</strong>
  <%= @person.license_type %>
</p>

<p>
  <strong>Occupation:</strong>
  <%= @person.occupation %>
</p>

<p>
  <strong>Street:</strong>
  <%= @person.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @person.city %>
</p>

<p>
  <strong>County:</strong>
  <%= @person.county %>
</p>

<p>
  <strong>License period:</strong>
  <%= @person.license_period %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @person.postcode %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>