config/routes.rb
Rails.application.routes.draw do
	namespace :api, defaults: {format: :json} do
		resources :people, except: [:new, :edit]
		resources :vehicles, except: [:new, :edit]
		resources :driver_histories, except: [:new, :edit]
		resources :quotes, except: [:new, :edit]
	end
  resources :driver_histories
  resources :vehicles
  resources :people
  resources :quotes

  root 'quotes#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
	validates_presence_of :mileage, :value, :registration

	belongs_to :quote, optional: true
end

app/controllers/api/vehicles_controller.rb
module Api
	class VehiclesController < ApplicationController
 
		before_action :set_vehicle, only: [:show, :update, :destroy]

  # GET /vehicles
  def index
    vehicles = Vehicle.all
    render json: {status: 'SUCCESS', message:'Loaded vehicles', data:vehicles},status: :ok
  end

  # GET /vehicles/1
  def show
	  vehicle = Vehicle.find(params[:id])
	  render json: {status: 'SUCCESS', message:'Loaded vehicle', data:vehicle},status: :ok
  end

  # POST /vehicles
  def create
    vehicle = Vehicle.new(vehicle_params)

    if vehicle.save
	    render json: {status: 'SUCCESS', message:'Saved vehicle', data:vehicle},status: :ok
    else  
	    render json: {status: 'ERROR', message:'Did not save vehicle', data:vehicle.errors},status: :unprocessable_entity
    end
  end

  # PATCH/PUT /vehicles/1
  def update
	  person = Person.find(params[:id])
    if vehicle.update(vehicle_params)
	    render json: {status: 'SUCCESS', message:'Updated vehicle', data:vehicle},status: :ok
    else
	    render json: {status: 'ERROR', message:'Did not update vehicle', data:vehicle.errors},status: :unprocessable_entity
    end
  end

  # DELETE /vehicles/1
  def destroy
	  vehicle = Vehicle.find(params[:id])
	  vehicle.destroy
	  render json: {status: 'SUCCESS', message:'Deleted vehicle', data:vehicle},status: :ok
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def vehicle_params
      params.require(:vehicle).permit(:registration, :mileage, :value, :parking_location, :policy_start)
    end
	end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to driver_history_url(:new), notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:registration, :mileage, :value, :parking_location, :policy_start)
    end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle, local: true) do |form| %>
  <% if vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :registration %>
    <%= form.text_field :registration %>
  </div>

  <div class="field">
    <%= form.label :mileage %>
    <%= form.number_field :mileage %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.number_field :value %>
  </div>

  <div class="field">
    <%= form.label :parking_location %>
    <%= form.text_field :parking_location %>
  </div>

  <div class="field">
    <%= form.label :policy_start %>
    <%= form.date_select :policy_start %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicles</h1>

<table>
  <thead>
    <tr>
      <th>Registration</th>
      <th>Mileage</th>
      <th>Value</th>
      <th>Parking location</th>
      <th>Policy start</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.registration %></td>
        <td><%= vehicle.mileage %></td>
        <td><%= vehicle.value %></td>
        <td><%= vehicle.parking_location %></td>
        <td><%= vehicle.policy_start %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle', new_vehicle_path %>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Registration:</strong>
  <%= @vehicle.registration %>
</p>

<p>
  <strong>Mileage:</strong>
  <%= @vehicle.mileage %>
</p>

<p>
  <strong>Value:</strong>
  <%= @vehicle.value %>
</p>

<p>
  <strong>Parking location:</strong>
  <%= @vehicle.parking_location %>
</p>

<p>
  <strong>Policy start:</strong>
  <%= @vehicle.policy_start %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>